# Ejercicios sobre lo aprendido

## Suban este notebook resuelto al drive con la nomenclatura nombre_apellido_TP_5

#### EJERCICIO 1
Debes utilizar numpy
1. ingresa por teclado la cantidad filas
2. ingresa por teclado la cantidad columnas
3. crea un arreglo de numpy de dimension filas columnas con elementos de tipo float.
4. rellena el array con 10.5
5. imprime shape, tipo y el arreglo

In [1]:
#creamos las variables a ingresar y las convertimos en enteros para obtener filas y columnas. Importamos el módulo numpy.

filas = input("ingrese número para cantidad de filas ")
filas=int(filas)
col=input("ingrese número para cantidad de columnas ")
col=int(col)
import numpy as np

ingrese número para cantidad de filas 3
ingrese número para cantidad de columnas 2


In [2]:
#creamos una matriz con los elementos randomizados tipo float por la cantidad de filas y columnas que ingresamos. Demostramos
#que nuestros elementos en la matriz creada son del tipo float.

meitrix=np.random.rand(filas,col)
type(meitrix[1][1])


numpy.float64

In [3]:
#aquí me ha fallado la interpretación, Iván. Por tanto, tomo la variable filas como la cantidad de elementos del vector que
#creamos a partirde esa variable y le agrego finalmente el 10.5 para la consigna 4. 

ej4=np.array(np.random.rand(filas))
ej4=np.append(ej4,[10.5])
print(ej4.shape)
print(type(ej4))
print(ej4)

(4,)
<class 'numpy.ndarray'>
[ 0.69441456  0.28963313  0.09632518 10.5       ]


#### EJERCICIO 2

Debes utilizar numpy

Ingrese al programa un numero entero 'n'. 

Crea un array de n elementos enteros consecutivos (de 0 a n).

Reformatea el array a un array cuadrado (reshape)

Imprima las dimensiones (ndim) , el tipo del array y el array 

In [4]:
#cumplimos hasta la creación del arreglo desde 0 hasta la n indicada.

elementos=input("ingrese un entero para el nuevo array: ")
elementos=int(elementos)
elementos=np.arange(elementos+1)
elementos

ingrese un entero para el nuevo array: 7


array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
#importo el módulo math para tener raíz cuadrada, luego corro un ciclo while hasta que mi cantidad de elementos del array creado
#sea posible de hacer raíz cuadrada entera, agregando un elemento por vuelta hasta que se cumpla la condición. Al poder hacerlo
#significa que puedo ya hacer una matriz cuadrada y allí aplico el reshape.

import math
while math.sqrt(len(elementos))%2!=0:
    elementos=np.append(elementos,[0])
elementos.reshape(int(math.sqrt(len(elementos))),int(math.sqrt(len(elementos))))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
print(f"dimensión: {elementos.ndim}")
print(f"tipo: {type(elementos)}")
print(f"array: {elementos}")

dimensión: 1
tipo: <class 'numpy.ndarray'>
array: [0 1 2 3 4 5 6 7 0 0 0 0 0 0 0 0]


#### EJERCICIO 3


Debes utilizar numpy 
1. crear una matriz de 3x3 con numeros enteros aleatorios (entre 1 y 50)
2. almacena en B la transpuesta de A
3. almacena en C el producto de A*B y en D la suma de A+B
4. imprime size de C y D
5. imprime shape de C y D
5. imprime C y D

In [7]:
#creo una matriz 3x3 y con el módulo random recorro la matriz y lo cambio por un aleatorio del 1 al 50

import random
A=np.random.rand(3,3)
for i in range (len(A)):
    for j in range (len(A[i])):
        A[i][j]=random.randint(1,50)
print(A)

[[21.  7. 26.]
 [12. 38. 15.]
 [33. 37. 13.]]


In [8]:
#creamos B a partir de la transpuesta de A
#creamos C por la multiplicación de A*B
#creamos D por la suma de A+B
#imprimimos lo pedido en consignas 4,5,6.

B=A.transpose()
C=A*B
D=A+B
print(f"size de C: {C.size}\nsize de D: {D.size}\n")
print(f"shape de C: {C.shape}\nshape de D: {D.shape}\n")
print(f"C:\n{C}\n")
print(f"D:\n{D}")


size de C: 9
size de D: 9

shape de C: (3, 3)
shape de D: (3, 3)

C:
[[ 441.   84.  858.]
 [  84. 1444.  555.]
 [ 858.  555.  169.]]

D:
[[42. 19. 59.]
 [19. 76. 52.]
 [59. 52. 26.]]


## Suban este notebook resuelto al drive con la nomenclatura nombre_apellido_TP_5